DROP TABLE IF EXISTS CLIENT;
CREATE TABLE CLIENT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(80) NOT NULL,
    lastname VARCHAR(80),
    docnumber VARCHAR(11)
);

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    description VARCHAR(255) NOT NULL,
    code VARCHAR(50),
    stock INT,
    price DECIMAL(11, 2)
);

DROP TABLE IF EXISTS INVOICE;
CREATE TABLE INVOICE (
    id INT PRIMARY KEY AUTO_INCREMENT,
    client_id INT,
    created_at DATETIME,
    total DECIMAL(11, 2)
);

DROP TABLE IF EXISTS INVOICE_DETAIL;
CREATE TABLE INVOICE_DETAIL (
    id INT PRIMARY KEY AUTO_INCREMENT,
    invoice_id INT,
    amount INT,
    product_id INT NOT NULL,
    price DECIMAL(11, 2),
    description VARCHAR(255) NOT NULL
);